### PR TITLE
Update to nix-2.0

### PR DESCRIPTION
**Pull request by infinity0**
Hey, I'm a [DD](https://qa.debian.org/developer.php?login=infinity0) and saw that you're working on this package. Thanks for starting it! I've made some updates, most significantly to get it working with nix-2.0.

Note this does *not* fix everything mentioned [in your review](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877331#31) but feel free to ask me for more detailed help.

### CODE REVIEW

**Comment by infinity0** [comment]
P.S I was just told about https://github.com/lamby/pkg-nix and maybe you could see if there's anything to be merged from that one. @lamby the author says on IRC `I don't plan to run with it` so I think it's obsolete and "the ball's in your court" as they say.

**Comment by lamby** [comment]
Thanks @infinity0. Yes, please consider https://github.com/lamby/pkg-nix obsolete. It was never uploaded anywhere. It worked once on my machine, although it did try and Compile The World as the base hashes didn't match anything upstream :3

**Comment by KaiHa** [comment]
Hi, thanks for your pull request. I am currently away from my computer but I will have a look at it as soon as I get home.

**Review by KaiHa — APPROVED** [review]

**Comment by KaiHa** [comment]
Hi @infinity0, thanks for your PR. I have merged it. I see one major complaint of lintian with nix version 2.0. 
```
E: nix source: license-problem-convert-utf-code src/linenoise/ConvertUTF.cpp                                                                                                                     
N:                                                                                                                                                                                               
N:    The following file source files include material under a non-free
N:    license from Unicode Inc. Therefore, it is not possible to ship this in
N:    main or contrib.
N:    
N:    This license does not grant any permission to modify the files (thus
N:    failing DFSG#3). Moreover, the license grant seems to attempt to
N:    restrict use to "products supporting the Unicode Standard" (thus failing
N:    DFSG#6).
N:    
N:    In this case a solution is to use libicu and to remove this code by
N:    repacking.
N:    
N:    If this is a false-positive, please report a bug against Lintian.
N:    
N:    Refer to https://bugs.debian.org/823100 for details.
N:    
N:    Severity: serious, Certainty: possible
N:    
N:    Check: cruft, Type: source
N: 
```

This is due to linenoise-ng which is included with nix. Do you have any recommendation how to handle this?

**Comment by infinity0** [comment]
@KaiHa Most likely, you'll need to report this to nix and/or linenoise-ng and have them rewrite the code to use [libicu](http://site.icu-project.org/download) instead of embedding `ConvertUTF.cpp` which apparently is [buggy and out-of-date](https://unicode.org/forum/viewtopic.php?f=9&t=90) anyways.

**Comment by infinity0** [comment]
I filed a bug to nix, let's see what they say.

**Comment by KaiHa** [comment]
> I filed a bug to nix, let's see what they say.

Reference to the [bug](https://github.com/NixOS/nix/issues/2014). Thanks @infinity0

**Pull request merged**
